### ISSUE TITLE
Support Request: SwitchBot not connecting through BLE

### ISSUE THREAD

**Issue by nmcc1212** [OpenWonderLabs/homebridge-switchbot#234]
Updated to latest version, having the same issue

@donavanbecker Sorry for late. I have updated the plugin to 1.7.0 (not 1.5.1-beta.5). But unsuccessful. When the plugin starts, it became generating an error as below:

[08/01/2022, 09:02:06] [SwitchBot] Total IR Devices Found: 0
[08/01/2022, 09:02:06] [SwitchBot] Bot: Bot 7E Using Bot Mode: switch
[08/01/2022, 09:02:06] [SwitchBot] Bot: Bot 7E Displaying as Switch
[08/01/2022, 09:02:07] [SwitchBot] Bot: Bot 7E wasn't able to establish BLE Connection
[08/01/2022, 09:02:07] [SwitchBot] Bot: Bot 7E Using OpenAPI Connection

As of above, now the plugin says it cannot establish BLE connection. Is this something I have to reconfigure? 
All settings are the same with my root article.

_Originally posted by @tzwada in https://github.com/OpenWonderLabs/homebridge-switchbot/issues/105#issuecomment-1007834024_

**Comment by donavanbecker** [comment]
Have you followed the [prerequisites](https://github.com/abandonware/noble#prerequisites) for noble? that is what makes the BLE connection.

**Comment by nmcc1212** [comment]
yes, i had this issue with a respberry pi but after reading your comments https://github.com/OpenWonderLabs/homebridge-switchbot/issues/221#issuecomment-1021247208 and here https://github.com/OpenWonderLabs/homebridge-switchbot/issues/221#issuecomment-1021534470i though it may be the fault of the respberry pi, so i installed it on a lenovo thinkpad t480s running ubuntu but still had the same issue.

to make sure i ran the command and it worked properly i tried the command again`sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev`and the output was 

```
bluez is already the newest version (5.60-0ubuntu2.1).
libbluetooth-dev is already the newest version (5.60-0ubuntu2.1).
libudev-dev is already the newest version (248.3-1ubuntu8.2).
bluetooth is already the newest version (5.60-0ubuntu2.1).
```

**Comment by donavanbecker** [comment]
@nmcc1212 for some reason node-swtichbot didn't install so you will have to find out why for BLE to work.

**Comment by nmcc1212** [comment]
I think there is an issue with homebridge-switchbot. Same happened here https://github.com/OpenWonderLabs/homebridge-switchbot/issues/221#issuecomment-1021066627

**Comment by donavanbecker** [comment]
@nmcc1212 what's that issue?

**Comment by nmcc1212** [comment]
in #221 node-switchbot also didn't install properly but it was blamed on the ras pi.

what im saying is it didnt work on my ras pi *or* a lenovo thinkpad. meaning it wasnt the fault of the ras pi

**Comment by nmcc1212** [comment]
also why is node-switchbot listed as an optional dependancy if it is needed for BLE?

https://github.com/OpenWonderLabs/homebridge-switchbot/blob/latest/package.json#L77#L78

**Comment by donavanbecker** [comment]
because if node-switchbot fails to install then the plugin will still install successfully. what you need to do is figure out why it is failing to install. 

this is not an issue with the plugin.

> in #221 node-switchbot also didn't install properly but it was blamed on the ras pi.
> 
> what im saying is it didnt work on my ras pi _or_ a lenovo thinkpad. meaning it wasnt the fault of the ras pi

doesn't mean its an issue with the plugin.

Closing till issue is found.

**Comment by nmcc1212** [comment]
node-switchbot is installed

```
npm list -g | grep switchbot
├── @switchbot/homebridge-switchbot@1.12.1
├── node-switchbot@1.1.2
```

**Comment by nmcc1212** [comment]
@donavanbecker here is the error i get *with node-switchbot installed*
```
[SwitchBot] Error: No service was found.
[SwitchBot] Retrying
[SwitchBot] Bot: Ceiling Light failed pushChanges with BLE Connection
[SwitchBot] Bot: Ceiling Light Using OpenAPI Connection
```

**Comment by donavanbecker** [comment]
@nmcc1212 Did you install it manually or with homebridge-switchbot?

**Comment by nmcc1212** [comment]
manually using `sudo npm install -g node-switchbot` as it didn't install with homebridge-switchbot

**Comment by tzwada** [comment]
@donavanbecker My problem was fixed. Here is what I've done.

1. Check if node-switchbot is installed.

```
npm list -g | grep switchbot
├── @eweiss/homebridge-switchbot-ble@1.6.5
├── @switchbot/homebridge-switchbot@1.7.0
```
No node-switchbot is installed.

2. Install node-switchbot.
```
sudo npm install -g node-switchbot
```

3. Update Homebridge.

Then, the BLE connection error was resolved. Now the Homebridge Switchbot is running. Can't be more excited! Thank you.

**Comment by nmcc1212** [comment]
what do you mean by update homebridge? update the npm package or restart homebridge?

**Comment by donavanbecker** [comment]
> manually using `sudo npm install -g node-switchbot` as it didn't install with homebridge-switchbot

That will not help. SwitchBot has to install it as a dependency. Only other option would be to try to reinstall homebridge-switchbot, if that doesn't work then there is some prerequisite that isn't being fulfilled.

**Comment by donavanbecker** [comment]
> @donavanbecker My problem was fixed. Here is what I've done.
> 
> 
> 
> 1. Check if node-switchbot is installed.
> 
> 
> 
> ```
> 
> npm list -g | grep switchbot
> 
> ├── @eweiss/homebridge-switchbot-ble@1.6.5
> 
> ├── @switchbot/homebridge-switchbot@1.7.0
> 
> ```
> 
> No node-switchbot is installed.
> 
> 
> 
> 2. Install node-switchbot.
> 
> ```
> 
> sudo npm install -g node-switchbot
> 
> ```
> 
> 
> 
> 3. Update Homebridge.
> 
> 
> 
> Then, the BLE connection error was resolved. Now the Homebridge Switchbot is running. Can't be more excited! Thank you.

I am guessing that these steps didn't resolve it. But glad it's working for you.

**Comment by nmcc1212** [comment]
> > manually using `sudo npm install -g node-switchbot` as it didn't install with homebridge-switchbot
> 
> That will not help. SwitchBot has to install it as a dependency. Only other option would be to try to reinstall homebridge-switchbot, if that doesn't work then there is some prerequisite that isn't being fulfilled.

do i need to remove node-switchbot before reinstalling homebridge-switchbot

**Comment by donavanbecker** [comment]
Don't have too
