### ISSUE TITLE
Bug: Air conditioner temperature not able to change

### ISSUE THREAD

**Issue by ilhuafbds** [OpenWonderLabs/homebridge-switchbot#43]
### Describe The Bug

Whenever I use the apple's native home app to change the temperature of my air conditioner, it doesn't change the temperature at all. And also, I always select the cooling mode when I turn on, but instead does heating. The number of the temperature i set using a remote controller and the temperature displayed on the apple home app doesn't sync. As you can see from the log, program has failed to send statusCode instead sending the value of %s,%s,%s,%s 

### To Reproduce

TOSHIBA air conditioner and change temperature from apple's home app 

### Expected behavior

Temperature not changing

### Relevant log output

```shell
[10/6/2021, 4:25:24 PM] [SwitchBot] Trigger Get CurrentTemperture
[10/6/2021, 4:25:24 PM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[10/6/2021, 4:25:24 PM] [@switchbot/homebridge-switchbot] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1456:24)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[10/6/2021, 4:26:48 PM] [SwitchBot] Sending request for Air conditioner  Air Conditioner to SwitchBot API. command: setAll parameter: %s,%s,%s,%s commandType: command
[10/6/2021, 4:26:48 PM] [SwitchBot] %s %s pushChanges -
[10/6/2021, 4:26:49 PM] [SwitchBot] %s %s Changes pushed -
[10/6/2021, 4:26:49 PM] [SwitchBot] Unknown statusCode.
[10/6/2021, 4:27:22 PM] [SwitchBot] Sending request for Air conditioner  Air Conditioner to SwitchBot API. command: setAll parameter: %s,%s,%s,%s commandType: command
[10/6/2021, 4:27:22 PM] [SwitchBot] %s %s pushChanges -
[10/6/2021, 4:27:23 PM] [SwitchBot] %s %s Changes pushed -
[10/6/2021, 4:27:23 PM] [SwitchBot] Unknown statusCode.
```

### Config for homebridge-switchbot

```shell
{
    "bridge": {
        "name": "Homebridge 2486",
        "username": "",
        "port":,
        "pin": ""
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "openToken": "",
                "notice": "Keep your token a secret!"
            },
            "platform": "SwitchBot"
        }
    ]
}
```

### Device & Model

WH-UB01UJ (model of air conditioner)
W0202200 (model of Switchbot hub mini)

### Node.js Version

v14.17.4

### NPM Version

v7.24.0

### Homebridge Version

v1.3.4

### Homebridge Switchbot Plugin Version

v0.1.1

### Homebridge Config UI X Plugin Version

v4.41.2

### Operating System

macOS

**Comment by ilhuafbds** [comment]
![IMG_1388](https://user-images.githubusercontent.com/78691566/136214452-769c2851-0b06-4647-9223-ba5b29d1ca2e.jpg)
This is how it looks on the switch bot app log whenever I try to change the temperature from the apple native home app.

**Comment by donavanbecker** [comment]
@ilhuafbds can you try the latest beta?

**Comment by ilhuafbds** [comment]
@donavanbecker I tried with the latest beta but it's still the same result

**Comment by ilhuafbds** [comment]
@donavanbecker Any updates?

**Comment by donavanbecker** [comment]
> @donavanbecker I tried with the latest beta but it's still the same result

the latest beta would not have the same logs so definitely can't be the same results. Can you post more logs from beta?

**Comment by ilhuafbds** [comment]
```
[10/13/2021, 6:29:18 PM] [SwitchBot] Air_conditioner Air Conditioner pushChanges - {"commandType":"command","parameter":"default","command":"turnOn"}
[10/13/2021, 6:29:19 PM] [SwitchBot] Air_conditioner Air Conditioner Changes pushed - [object Object]
[10/13/2021, 6:29:19 PM] [SwitchBot] Command successfully sent.
[10/13/2021, 6:29:34 PM] [SwitchBot] Sending request for Air_conditioner Air Conditioner to SwitchBot API. command: setAll parameter: 23,1,1,on commandType: command
[10/13/2021, 6:29:34 PM] [SwitchBot] Air_conditioner Air Conditioner pushChanges - {"commandType":"command","command":"setAll","parameter":"23,1,1,on"}
[10/13/2021, 6:29:35 PM] [SwitchBot] Air_conditioner Air Conditioner Changes pushed - [object Object]
[10/13/2021, 6:29:35 PM] [SwitchBot] Unknown statusCode.
[10/13/2021, 6:29:39 PM] [SwitchBot] Air_conditioner Air Conditioner Set Active: 1
[10/13/2021, 6:29:41 PM] [SwitchBot] Sending request for Air_conditioner Air Conditioner to SwitchBot API. command: setAll parameter: 23,1,1,on commandType: command
[10/13/2021, 6:29:41 PM] [SwitchBot] Air_conditioner Air Conditioner pushChanges - {"commandType":"command","command":"setAll","parameter":"23,1,1,on"}
[10/13/2021, 6:29:42 PM] [SwitchBot] Air_conditioner Air Conditioner Changes pushed - [object Object]
[10/13/2021, 6:29:42 PM] [SwitchBot] Unknown statusCode.
[10/13/2021, 6:29:46 PM] [SwitchBot] Air_conditioner Air Conditioner Set Active: 1
[10/13/2021, 6:29:47 PM] [SwitchBot] Sending request for Air_conditioner Air Conditioner to SwitchBot API. command: setAll parameter: 23,1,1,on commandType: command
[10/13/2021, 6:29:47 PM] [SwitchBot] Air_conditioner Air Conditioner pushChanges - {"commandType":"command","command":"setAll","parameter":"23,1,1,on"}
[10/13/2021, 6:29:48 PM] [SwitchBot] Air_conditioner Air Conditioner Changes pushed - [object Object]
[10/13/2021, 6:29:48 PM] [SwitchBot] Unknown statusCode.
[10/13/2021, 6:30:06 PM] [SwitchBot] Air_conditioner Air Conditioner Set Active: 0
[10/13/2021, 6:30:06 PM] [SwitchBot] Sending request for Air_conditioner Air Conditioner to SwitchBot API. command: turnOff parameter: default commandType: command
[10/13/2021, 6:30:06 PM] [SwitchBot] Air_conditioner Air Conditioner pushChanges - {"commandType":"command","parameter":"default","command":"turnOff"}
[10/13/2021, 6:30:07 PM] [SwitchBot] Air_conditioner Air Conditioner Changes pushed - [object Object]
[10/13/2021, 6:30:07 PM] [SwitchBot] Command successfully sent.

**Comment by ilhuafbds** [comment]
```
[10/13/2021, 6:28:22 PM] [SwitchBot] Trigger Get CurrentTemperture
[10/13/2021, 6:28:22 PM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[10/13/2021, 6:28:22 PM] [@switchbot/homebridge-switchbot] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2074:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1967:16)
    at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1492:24)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by ilhuafbds** [comment]
@donavanbecker Thanks for the update! But I still can't change the temperature from my apple home app...

**Comment by donavanbecker** [comment]
@ilhuafbds When I get time I will look into this

**Comment by donavanbecker** [comment]
@ilhuafbds, can you try Beta: 

[![npm version](https://badgen.net/npm/v/@switchbot/homebridge-switchbot/beta)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

**Comment by JB4Lyfe** [comment]
> @ilhuafbds, can you try Beta:
> 
> [![npm version](https://camo.githubusercontent.com/7bec61e2dae4bbe99d80cfed311a2e18c460b2f3e982f194df9324d492df9e7d/68747470733a2f2f62616467656e2e6e65742f6e706d2f762f40737769746368626f742f686f6d656272696467652d737769746368626f742f62657461)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

Can confirm the latest beta v0.1.2-bueta.39 does not work. Comes up with he same error.

**Comment by donavanbecker** [comment]
@JB4Lyfe pleas post the error again

**Comment by JB4Lyfe** [comment]
Here!. Thanks
![IMG_0694](https://user-images.githubusercontent.com/40929699/137847534-0c5df826-5ebb-4e51-b66c-4b0b308343f1.PNG)
.

**Comment by donavanbecker** [comment]
Didn't finish uploading

**Comment by ilhuafbds** [comment]
```[10/19/2021, 6:31:29 PM] [SwitchBot] Sending request for Air_conditioner to SwitchBot API. command: turnOn parameter: default commandType: command
[10/19/2021, 6:31:29 PM] [SwitchBot] Air_conditioner pushChanges - {"commandType":"command","parameter":"default","command":"turnOn"}
[10/19/2021, 6:31:30 PM] [SwitchBot] Air_conditioner Changes pushed - [object Object]
[10/19/2021, 6:31:30 PM] [SwitchBot] Command successfully sent.
[10/19/2021, 6:31:30 PM] [SwitchBot] Sending request for Air_conditioner to SwitchBot API. command: setAll parameter: 24,1,1,on commandType: command
[10/19/2021, 6:31:30 PM] [SwitchBot] Air_conditioner pushChanges - {"commandType":"command","command":"setAll","parameter":"24,1,1,on"}
[10/19/2021, 6:31:31 PM] [SwitchBot] Air_conditioner Changes pushed - [object Object]
[10/19/2021, 6:31:31 PM] [SwitchBot] Unknown statusCode.
[10/19/2021, 6:31:38 PM] [SwitchBot] Sending request for Air_conditioner to SwitchBot API. command: setAll parameter: 21,1,1,on commandType: command
[10/19/2021, 6:31:38 PM] [SwitchBot] Air_conditioner pushChanges - {"commandType":"command","command":"setAll","parameter":"21,1,1,on"}
[10/19/2021, 6:31:39 PM] [SwitchBot] Air_conditioner Changes pushed - [object Object]
[10/19/2021, 6:31:39 PM] [SwitchBot] Unknown statusCode.
[10/19/2021, 6:31:59 PM] [SwitchBot] Sending request for Air_conditioner to SwitchBot API. command: setAll parameter: 27,1,1,on commandType: command
[10/19/2021, 6:31:59 PM] [SwitchBot] Air_conditioner pushChanges - {"commandType":"command","command":"setAll","parameter":"27,1,1,on"}
[10/19/2021, 6:32:00 PM] [SwitchBot] Air_conditioner Changes pushed - [object Object]
[10/19/2021, 6:32:00 PM] [SwitchBot] Unknown statusCode.
[10/19/2021, 6:32:06 PM] [SwitchBot] Air_conditioner Set Active: 0
[10/19/2021, 6:32:06 PM] [SwitchBot] Sending request for Air_conditioner to SwitchBot API. command: turnOff parameter: default commandType: command
[10/19/2021, 6:32:06 PM] [SwitchBot] Air_conditioner pushChanges - {"commandType":"command","parameter":"default","command":"turnOff"}
[10/19/2021, 6:32:07 PM] [SwitchBot] Air_conditioner Changes pushed - [object Object]
[10/19/2021, 6:32:07 PM] [SwitchBot] Command successfully sent.

**Comment by ilhuafbds** [comment]
Sorry for the late reply. It's still not working on the latest bata...

**Comment by donavanbecker** [comment]
@ilhuafbds Are those other commands from the SwitchBot app or the plugin?

**Comment by ilhuafbds** [comment]
The log I posted is copied from the homebridge server log.

**Comment by donavanbecker** [comment]
I'm talking about the screenshot

**Comment by ilhuafbds** [comment]
@donavanbecker It's all the commands made when I tried to change the temperature from the apple home app.

**Comment by ilhuafbds** [comment]
When I change the temperature from the Switchbot app it works just fine.

**Comment by 618116** [comment]
I have a same issue.

This log is from HomeBridge Plugin:

> [10/24/2021, 9:15:08 PM] [SwitchBot] Sending request for エアコン to SwitchBot API. command: setAll parameter: 24,1,1,on commandType: command
> [10/24/2021, 9:15:08 PM] [SwitchBot] [DEBUG] エアコン pushChanges - {"commandType":"command","command":"setAll","parameter":"24,1,1,on"}
> [10/24/2021, 9:15:09 PM] [SwitchBot] [DEBUG] エアコン Changes pushed - [object Object]
> [10/24/2021, 9:15:09 PM] [SwitchBot] [DEBUG] Unknown statusCode.

and on log of SwitchBot App, it is said "error (172)".

**Comment by ilhuafbds** [comment]
@donavanbecker Any updates?

**Comment by donavanbecker** [comment]
@ilhuafbds, no. I have a life to attend to and only do this on my free time. Please have patients.

**Comment by donavanbecker** [comment]
@ilhuafbds and @JB4Lyfe, I just pushed a new beta out can you try it?

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/0.1.4-beta.3/orange)](https://www.npmjs.com/package/homebridge-honeywell-home)

**Comment by 618116** [comment]
It seems new beta version software cannot recognize my Hub mini. Every IR devices are not shown on HomeBridge.

**Comment by 618116** [comment]
Here is a Debug log from 0.1.4-beta3 .
`{"statusCode":100,"body":{"deviceList":[{"deviceId":"EDD7CB717E17","deviceName":"Cho's Hub Mini","deviceType":"Hub Mini","hubDeviceId":"000000000000"},{"deviceId":"F47BC970D7A5","deviceName":"カーテン","deviceType":"Curtain","enableCloudService":true,"hubDeviceId":"EDD7CB717E17","curtainDevicesIds":["F47BC970D7A5"],"calibrate":true,"group":false,"master":true,"openDirection":"left"},{"deviceId":"F616355A82A9","deviceName":"温湿度計","deviceType":"Meter","enableCloudService":true,"hubDeviceId":"EDD7CB717E17"}],"infraredRemoteList":[{"deviceId":"02-202110190736-52839243","deviceName":"ライト2","remoteType":"Light","hubDeviceId":"EDD7CB717E17"},{"deviceId":"02-202110190737-58148629","deviceName":"ライト1","remoteType":"Light","hubDeviceId":"EDD7CB717E17"},{"deviceId":"02-202111062211-57539880","deviceName":"エアコン","remoteType":"Air Conditioner","hubDeviceId":"EDD7CB717E17"}]},"message":"success"}`

**Comment by ilhuafbds** [comment]
```
DIR: /usr/local
CMD: npm install -g @switchbot/homebridge-switchbot@0.1.4-beta.3

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@switchbot/homebridge-switchbot@0.1.4-beta.3',
npm WARN EBADENGINE   required: { homebridge: '^1.3.5', node: '^14.18.1 || ^16.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.17.4', npm: '7.24.0' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.17.4 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.0 found at "/usr/local/bin/python3"
npm ERR! gyp info spawn /usr/local/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users//Library/Caches/node-gyp/14.17.4/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users//Library/Caches/node-gyp/14.17.4',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users//Library/Caches/node-gyp/14.17.4/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Darwin 21.1.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/@switchbot/homebridge-switchbot/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v14.17.4
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users//.npm/_logs/2021-11-07T09_45_00_125Z-debug.log

Command failed. Please review log for details.
```

**Comment by ilhuafbds** [comment]
@donavanbecker When I tried to install your latest beta, an error showed up and I couldn't install it.

**Comment by donavanbecker** [comment]
@ilhuafbds Did you read the warning? You need to update your node version.

**Comment by donavanbecker** [comment]
@ilhuafbds and @618116, sorry latest beta should work now.

**Comment by 618116** [comment]
Tested new beta, unfortunately it did not work.
Turn On and Off Air Conditioner works, however Set temperature does not works and there is Error(172) in SwitchBot app log.

This is log from HomeBridge plugin Debug mode when turn on Air Conditioner with setting "24℃, Heater" in iOS Home app:

> [11/13/2021, 11:29:30 PM] [SwitchBot] [DEBUG] エアコン Set Active: 1
> [11/13/2021, 11:29:30 PM] [SwitchBot] Sending request for エアコン to SwitchBot API. command: turnOn parameter: default commandType: command
> [11/13/2021, 11:29:30 PM] [SwitchBot] [DEBUG] エアコン pushChanges - {"commandType":"command","parameter":"default","command":"turnOn"}
> [11/13/2021, 11:29:31 PM] [SwitchBot] [DEBUG] エアコン Changes pushed - [object Object]
> [11/13/2021, 11:29:31 PM] [SwitchBot] [DEBUG] Command successfully sent.
> [11/13/2021, 11:29:32 PM] [SwitchBot] Sending request for エアコン to SwitchBot API. command: setAll parameter: 24,1,1,on commandType: command
> [11/13/2021, 11:29:32 PM] [SwitchBot] [DEBUG] エアコン pushChanges - {"commandType":"command","command":"setAll","parameter":"24,1,1,on"}
> [11/13/2021, 11:29:33 PM] [SwitchBot] [DEBUG] エアコン Changes pushed - [object Object]
> [11/13/2021, 11:29:33 PM] [SwitchBot] [DEBUG] Unknown statusCode.

And SwitchBot app had 2 logs:

> "On, Heater, Auto, 25℃", "Error(172)"

**Comment by donavanbecker** [comment]
Version 1.2.0 has been released, Please update me on this, and if it has been resolved with this version.

**Comment by 618116** [comment]
Unfortunately, still not fixed. Below is log from Homebridge when trying to turn on with 29℃ setting.

```> 11/20/2021, 2:53:19 PM] [SwitchBot] [DEBUG] Air Conditioner: エアコン Set Active: 1
> [11/20/2021, 2:53:19 PM] [SwitchBot] Air Conditioner: エアコン Sending request to SwitchBot API. command: turnOn, parameter: default, commandType: command
> [11/20/2021, 2:53:21 PM] [SwitchBot] [DEBUG] Air Conditioner: エアコン pushChanges: [object Object]
> [11/20/2021, 2:53:21 PM] [SwitchBot] [DEBUG] Air Conditioner: エアコン Command successfully sent.
> [11/20/2021, 2:53:21 PM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Active': characteristic was supplied illegal value: number 29 exceeded maximum of 1. See https://git.io/JtMGR for more info.
> [11/20/2021, 2:53:21 PM] [SwitchBot] [DEBUG] Air Conditioner: エアコン TargetHeaterCoolerState: undefined
> [11/20/2021, 2:53:21 PM] [SwitchBot] [DEBUG] Air Conditioner: エアコン HeatingThresholdTemperature: undefined```

SwitchBot app log shows only "turn on, heat, auto, 24℃" log.

Also If I try to change temperature in home app, SwitchBot app log shows Error(172).

**Comment by jhy-dabeeo** [comment]
Hi i have Air conditioner temperature changing issue too

this is my log. i can't find issue related my error type so write here
i just updated plugin 1.2.0 but still got errors when change temperature while turn on/off is fine.

```
[20/11/2021, 19:45:30] [SwitchBot] Air Conditioner: Air conditioner Sending request to SwitchBot API. command: turnOn, parameter: default, commandType: command
[20/11/2021, 19:45:32] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic Active: 1
[20/11/2021, 19:45:32] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic RotationSpeed: 4
[20/11/2021, 19:45:32] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic CurrentTemperature: 24
[20/11/2021, 19:45:32] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic CurrentHeaterCoolerState: 0
[20/11/2021, 19:45:42] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner CurrentTemperature: 20, LastTemperature: 24
[20/11/2021, 19:45:43] [SwitchBot] Air Conditioner: Air conditioner Sending request to SwitchBot API. command: setAll, parameter: 20,1,1,on, commandType: command
[20/11/2021, 19:45:44] [SwitchBot] Air Conditioner: Air conditioner Device internal error due to device states not synchronized with server, Or command: {"statusCode":190,"body":{},"message":"Cannot read property 'toString' of null"} format is invalid
[20/11/2021, 19:45:44] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic Active: 1
[20/11/2021, 19:45:44] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic RotationSpeed: 4
[20/11/2021, 19:45:44] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic CurrentTemperature: 20
[20/11/2021, 19:45:44] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic CurrentHeaterCoolerState: 3
[20/11/2021, 19:45:47] [SwitchBot] Air Conditioner: Air conditioner Sending request to SwitchBot API. command: turnOff, parameter: default, commandType: command
[20/11/2021, 19:45:48] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic Active: 0
[20/11/2021, 19:45:48] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic RotationSpeed: 4
[20/11/2021, 19:45:48] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Active': characteristic was supplied illegal value: number 20 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[20/11/2021, 19:45:48] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic CurrentTemperature: 20
[20/11/2021, 19:45:48] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner updateCharacteristic CurrentHeaterCoolerState: 3
[20/11/2021, 19:46:16] [SwitchBot] [DEVICE] Air Conditioner: Air conditioner CurrentHeaterCoolerState: 0```

**Comment by hughfr4nc15** [comment]
Having the same issue with a Mitsubishi AC. Tried 1.2.1 beta but still got the errors.
Also when I turn it OFF in the Home App it briefly shows as OFF but then ON again although it is turning OFF. Have to click it again to show OFF.

Log:
```
[23/11/2021, 22:57:05] [Homebridge UI] Homebridge restart request received
[23/11/2021, 22:57:05] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[23/11/2021, 22:57:05] [Homebridge UI] Sending SIGTERM to Homebridge
[23/11/2021, 22:57:05] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
[23/11/2021, 22:57:10] [HB Supervisor] Restarting Homebridge...
[23/11/2021, 22:57:10] [HB Supervisor] Starting Homebridge with extra flags: -I
[23/11/2021, 22:57:10] [HB Supervisor] Started Homebridge v1.3.8 with PID: 7556
[23/11/2021, 22:57:11] Loaded config.json with 0 accessories and 4 platforms.
[23/11/2021, 22:57:11] Loaded 4 cached accessories from cachedAccessories.
[23/11/2021, 22:57:11] ---
[23/11/2021, 22:57:11] Loaded plugin: homebridge-config-ui-x@4.41.2
[23/11/2021, 22:57:11] Registering platform 'homebridge-config-ui-x.config'
[23/11/2021, 22:57:11] ---
[23/11/2021, 22:57:11] Loaded plugin: homebridge-samsung-tizen@5.1.0
[23/11/2021, 22:57:11] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[23/11/2021, 22:57:11] ---
[23/11/2021, 22:57:11] Loaded plugin: homebridge-shelly@0.19.1
[23/11/2021, 22:57:11] Registering platform 'homebridge-shelly.Shelly'
[23/11/2021, 22:57:11] ---
[23/11/2021, 22:57:12] Loaded plugin: @switchbot/homebridge-switchbot@1.2.0
[23/11/2021, 22:57:12] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[23/11/2021, 22:57:12] ---
[23/11/2021, 22:57:12] Loading 4 platforms...
[23/11/2021, 22:57:12] [Homebridge] Initializing config platform...
[23/11/2021, 22:57:12] [Homebridge] Running in Service Mode
[23/11/2021, 22:57:12] [SamsungTizen] Initializing SamsungTizen platform...
[23/11/2021, 22:57:12] [Shelly] Initializing Shelly platform...
[23/11/2021, 22:57:12] [SwitchBot] Initializing SwitchBot platform...
[23/11/2021, 22:57:12] [SwitchBot] Initializing child bridge 0E:B7:F5:44:78:2D

[...]

[23/11/2021, 22:57:12] [SwitchBot] Launched child bridge with PID 7376
[23/11/2021, 22:57:13] Registering platform '@switchbot/homebridge-switchbot.SwitchBot'
[23/11/2021, 22:57:13] [SwitchBot] Loaded @switchbot/homebridge-switchbot v1.2.0 child bridge successfully
[23/11/2021, 22:57:13] Loaded 2 cached accessories from cachedAccessories.0EB7F544782D.
[23/11/2021, 22:57:13] [SwitchBot] Using Default Refresh Rate (2 minutes).
[23/11/2021, 22:57:13] [SwitchBot] Using Default Push Rate.
[23/11/2021, 22:57:13] [SwitchBot] Loading accessory from cache: Master Bedroom AC
[23/11/2021, 22:57:13] [SwitchBot] Loading accessory from cache: Master Bedroom Meter
[23/11/2021, 22:57:13] Homebridge v1.3.8 (HAP v0.9.7) (SwitchBot) is running on port 47274.
[23/11/2021, 22:57:13] [SwitchBot] [DEBUG] {"statusCode":100,"body":{"deviceList":[{"deviceId":"C9EC03C1F591","deviceName":"Master Bedroom Meter","deviceType":"Meter","enableCloudService":true,"hubDeviceId":"D680602B728C"},{"deviceId":"D680602B728C","deviceName":"Master Bedroom Hub Mini","deviceType":"Hub Mini","hubDeviceId":"000000000000"}],"infraredRemoteList":[{"deviceId":"02-202111231606-62857792","deviceName":"Master Bedroom AC","remoteType":"Air Conditioner","hubDeviceId":"D680602B728C"}]},"message":"success"}
[23/11/2021, 22:57:13] [SwitchBot] Total SwitchBot Devices Found: 2
[23/11/2021, 22:57:13] [SwitchBot] [DEBUG] SwitchBot Device Config Not Set: undefined
[23/11/2021, 22:57:13] [SwitchBot] [DEBUG] Discovered Meter: C9EC03C1F591
[23/11/2021, 22:57:13] [SwitchBot] Restoring existing accessory from cache: Master Bedroom Meter DeviceID: C9EC03C1F591
[23/11/2021, 22:57:13] [SwitchBot] [DEBUG] Discovered Hub Mini: D680602B728C
[23/11/2021, 22:57:13] [SwitchBot] Total IR Devices Found: 1
[23/11/2021, 22:57:13] [SwitchBot] [DEBUG] IR Device Config Not Set: undefined
[23/11/2021, 22:57:13] [SwitchBot] [DEBUG] Discovered Air Conditioner: 02-202111231606-62857792
[23/11/2021, 22:57:13] [SwitchBot] Restoring existing accessory from cache: Master Bedroom AC DeviceID: 02-202111231606-62857792
[23/11/2021, 22:57:13] [SwitchBot] [DEBUG] Air Conditioner uuid: 02-202111231606-62857792-Air Conditioner, (93e6df79-d302-4932-a248-a0121ebee952)
[23/11/2021, 22:57:13] [SwitchBot] [DEBUG] Meter: Master Bedroom Meter OpenAPI RefreshStatus
[23/11/2021, 22:57:13] [SwitchBot] [DEBUG] Meter uuid: C9EC03C1F591-Meter, (b9047841-30d0-48c5-a6fa-1aebee794bde)
[23/11/2021, 22:57:14] [SwitchBot] [DEBUG] Trigger Get CurrentTemperture
[23/11/2021, 22:57:14] [SwitchBot] [DEBUG] Meter: Master Bedroom Meter openAPIRefreshStatus: {"statusCode":100,"body":{"deviceId":"C9EC03C1F591","deviceType":"Meter","hubDeviceId":"D680602B728C","humidity":58,"temperature":21.7},"message":"success"}
[23/11/2021, 22:57:14] [SwitchBot] [DEBUG] Meter: Master Bedroom Meter OpenAPI parseStatus
[23/11/2021, 22:57:14] [SwitchBot] [DEBUG] Meter: Master Bedroom Meter Humidity: 58%
[23/11/2021, 22:57:14] [SwitchBot] [DEBUG] Meter: Master Bedroom Meter Temperature: 21.7°c
[23/11/2021, 22:57:34] [SwitchBot] [DEBUG] Trigger Get CurrentTemperture
[23/11/2021, 22:57:51] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC Set Active: 1
[23/11/2021, 22:57:51] [SwitchBot] Air Conditioner: Master Bedroom AC Sending request to SwitchBot API. command: turnOn, parameter: default, commandType: command
[23/11/2021, 22:57:52] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC pushChanges: [object Object]
[23/11/2021, 22:57:52] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC Command successfully sent.
[23/11/2021, 22:57:52] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Active': characteristic was supplied illegal value: number 24 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[23/11/2021, 22:57:52] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC TargetHeaterCoolerState: undefined
[23/11/2021, 22:57:52] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC HeatingThresholdTemperature: undefined
[23/11/2021, 22:57:53] [SwitchBot] Air Conditioner: Master Bedroom AC Sending request to SwitchBot API. command: setAll, parameter: 24,1,1,on, commandType: command
[23/11/2021, 22:57:53] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC pushChanges: [object Object]
[23/11/2021, 22:57:53] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC Unknown statusCode.
[23/11/2021, 22:57:53] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Active': characteristic was supplied illegal value: number 24 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[23/11/2021, 22:57:53] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC TargetHeaterCoolerState: undefined
[23/11/2021, 22:57:53] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC HeatingThresholdTemperature: undefined
[23/11/2021, 22:58:00] [SwitchBot] Air Conditioner: Master Bedroom AC Sending request to SwitchBot API. command: setAll, parameter: 25,1,1,on, commandType: command
[23/11/2021, 22:58:01] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC pushChanges: [object Object]
[23/11/2021, 22:58:01] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC Unknown statusCode.
[23/11/2021, 22:58:01] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Active': characteristic was supplied illegal value: number 25 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[23/11/2021, 22:58:01] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC TargetHeaterCoolerState: undefined
[23/11/2021, 22:58:01] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC HeatingThresholdTemperature: undefined
[23/11/2021, 22:58:09] [SwitchBot] Air Conditioner: Master Bedroom AC Sending request to SwitchBot API. command: setAll, parameter: 24,1,1,on, commandType: command
[23/11/2021, 22:58:10] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC pushChanges: [object Object]
[23/11/2021, 22:58:10] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC Unknown statusCode.
[23/11/2021, 22:58:10] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Active': characteristic was supplied illegal value: number 24 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[23/11/2021, 22:58:10] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC TargetHeaterCoolerState: undefined
[23/11/2021, 22:58:10] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC HeatingThresholdTemperature: undefined
[23/11/2021, 22:58:14] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC Set Active: 0
[23/11/2021, 22:58:14] [SwitchBot] Air Conditioner: Master Bedroom AC Sending request to SwitchBot API. command: turnOff, parameter: default, commandType: command
[23/11/2021, 22:58:15] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC pushChanges: [object Object]
[23/11/2021, 22:58:15] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC Command successfully sent.
[23/11/2021, 22:58:15] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Active': characteristic was supplied illegal value: number 24 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[23/11/2021, 22:58:15] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC TargetHeaterCoolerState: undefined
[23/11/2021, 22:58:15] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC HeatingThresholdTemperature: undefined
[23/11/2021, 22:58:17] [SwitchBot] [DEBUG] Air Conditioner: Master Bedroom AC Set Active: 0
```
Let me know if I can provide anything more useful.

Thanks.

**Comment by donavanbecker** [comment]
@hughfr4nc15 @618116 @jhy-dabeeo @ilhuafbds, can you try Beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.2.6-beta.0/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by hughfr4nc15** [comment]
Hello @donavanbecker, I've returned the equipments a couple of days after... If in the near future all works well I might try them again because they seem a cheap alternative to control the AC.

I'll keep following the project.

Thanks.

**Comment by jhy-dabeeo** [comment]
update 1.3.0 but still got errors

[06/12/2021, 21:48:04] [SwitchBot] Air Conditioner: Air conditioner pushChanges: {"statusCode":190,"body":{},"message":"Cannot read property 'toString' of null"}
[06/12/2021, 21:48:04] [SwitchBot] Air Conditioner: Air conditioner Device internal error due to device states not synchronized with server, Or command: {"statusCode":190,"body":{},"message":"Cannot read property 'toString' of null"} format is invalid

**Comment by 618116** [comment]
Tried 1.3.1-beta1 13. Not fixed.

Log from HomeBridge: 
`[12/13/2021, 7:38:27 PM] [SwitchBot] [DEBUG] Air Conditioner: エアコン pushChanges: [object Object]
[12/13/2021, 7:38:27 PM] [SwitchBot] [DEBUG] Air Conditioner: エアコン Unknown statusCode.
[12/13/2021, 7:38:27 PM] [@switchbot/homebridge-switchbot] This plugin generated a warning from the characteristic 'Active': characteristic was supplied illegal value: number 27 exceeded maximum of 1. See https://git.io/JtMGR for more info.
[12/13/2021, 7:38:27 PM] [SwitchBot] [DEBUG] Air Conditioner: エアコン TargetHeaterCoolerState: undefined
[12/13/2021, 7:38:27 PM] [SwitchBot] [DEBUG] Air Conditioner: エアコン HeatingThresholdTemperature: undefined`

SwitchBot App returned Error(172).

**Comment by y-mamanaranu** [comment]
I have the same problem with 1.4.0 and get the logs below.
It seems this plugin push `[temperture, 1, 1, on]` regardless of `HeaterCoolerState`, which I set in the UI.
The second paramter indicate `HeaterCoolerState`: https://github.com/OpenWonderLabs/SwitchBotAPI.
All error logs shown in this thread also push the parameters with the same form above.

```
[12/18/2021, 12:57:56 PM] [SwitchBot] Air Conditioner: MyDeviceName Sending request to SwitchBot API. command: setAll, parameter: [21,1,1,on], commandType: command
[12/18/2021, 12:57:57 PM] [SwitchBot] Air Conditioner: MyDeviceName pushChanges: {"statusCode":190,"body":{},"message":"Cannot read property 'length' of null"}
[12/18/2021, 12:57:57 PM] [SwitchBot] Air Conditioner: MyDeviceName Device internal error due to device states not synchronized with server, Or command: {"statusCode":190,"body":{},"message":"Cannot read property 'length' of null"} format is invalid
```

I also tested the native SwitchBot API on python and found the facts below.
First, With auto mode (`HeaterCoolerState=1`), my air conditioner allows only 25 degrees, i.e., parameters of `[25, 1, 1, on]`.
This plugin also successfully changed my air conditioner under this condition and got logs below.
My SwitchBot app also fixes the temper with 25 degrees with auto mode.

```
[12/18/2021, 1:07:27 PM] [SwitchBot] Air Conditioner: MyDeviceName Sending request to SwitchBot API. command: setAll, parameter: [25,1,1,on], commandType: command
[12/18/2021, 1:07:28 PM] [SwitchBot] Air Conditioner: MyDeviceName pushChanges: {"statusCode":100,"body":{},"message":"success"}
```

Second, It seems that the IR devices have no method to get the current state: https://github.com/OpenWonderLabs/SwitchBotAPI.
So, I think some problems occur around updating the current state.

I will share the results of my research so far.

**Comment by donavanbecker** [comment]
> I also tested the native SwitchBot API on python and found the facts below. First, With auto mode (`HeaterCoolerState=1`), my air conditioner allows only 25 degrees, i.e., parameters of `[25, 1, 1, on]`. This plugin also successfully changed my air conditioner under this condition and got logs below. My SwitchBot app also fixes the temper with 25 degrees with auto mode.
> 

Thanks @y-muen!!! I have implemented this into that last beta. This should fix mostly everything.

@ilhuafbds @618116 @hughfr4nc15 @jhy-dabeeo, can you try the latest beta: 

[![npm version](https://badgen.net/badge/homebridge-switchbot@beta/>=1.4.1-beta.6/orange)](https://www.npmjs.com/package/@switchbot/homebridge-switchbot)

[Click here to find out how to install Beta](https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Beta-Version)

**Comment by donavanbecker** [comment]
> I also tested the native SwitchBot API on python and found the facts below. First, With auto mode (`HeaterCoolerState=1`), my air conditioner allows only 25 degrees, i.e., parameters of `[25, 1, 1, on]`. This plugin also successfully changed my air conditioner under this condition and got logs below. My SwitchBot app also fixes the temper with 25 degrees with auto mode.
> 

Thanks @y-muen!!! I have implemented this into that last beta. This should fix mostly everything.


Released v1.5.0, which fixes this issue, so closing issue. If other issues come up with Air Conditioner, please open new issue.
