### ISSUE TITLE
Support Request: Bluetooth HCI socket failing to download 

### ISSUE THREAD

**Issue by xhi-nico** [OpenWonderLabs/homebridge-switchbot#511]
### Describe Your Problem

Every time I try to install the plugin, the Bluetooth HCI socket repository fails to download

### Relevant log output

```shell
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth_hci_socket-0.5.3-8-node-v93-linux-arm.tar.gz
```

### Device & Model

Raspberry Pi 3+

### Node.js Version

LATEST

### NPM Version

LATEST

### Homebridge Version

LATEST

### Homebridge SwitchBot Plugin Version

LATEST

### Operating System

Raspbian

**Comment by xhi-nico** [comment]
I understand this may not be related to your plugin though I wanted to see if I am doing something wrong here?

**Comment by donavanbecker** [comment]
@GeorgeeNico did you follow the noble [prerequisites](https://github.com/abandonware/noble#prerequisites)?

**Comment by GeorgeeNico** [comment]
Fixed on latest beta! No delay at all. 

[12/10/2022, 20:55:08] [SwitchBot] Bot: Door Buzzer Set On: true
[12/10/2022, 20:55:08] [SwitchBot] Bot: Door Buzzer Sending request to SwitchBot API. body: {"command":"press","parameter":"default","commandType":"command"}

**Comment by xhi-nico** [comment]
Followed the prerequisites and this is the error I get when trying to install noble:

```
pi@homebridge:/var/lib/homebridge $ npm install @abandonware/noble
npm ERR! code 1
npm ERR! path /var/lib/homebridge/node_modules/@abandonware/noble
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make: Entering directory '/var/lib/homebridge/node_modules/@abandonware/noble/build'
npm ERR!   SOLINK_MODULE(target) Release/obj.target/noble.node
npm ERR! make: Leaving directory '/var/lib/homebridge/node_modules/@abandonware/noble/build'
npm ERR! /usr/bin/ld: error while loading shared libraries: /lib/arm-linux-gnueabihf/libbfd-2.35.2-system.so: nonzero padding in e_ident
npm ERR! collect2: error: ld returned 127 exit status
npm ERR! make: *** [noble.target.mk:20: Release/obj.target/noble.node] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.15.32-v7+
npm ERR! gyp ERR! command "/opt/homebridge/bin/node" "/opt/homebridge/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /var/lib/homebridge/node_modules/@abandonware/noble
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-10-13T01_01_39_453Z-debug-0.log
```

I got around it by using the command "**_pi@homebridge:/var/lib/homebridge $ npm install @abandonware/noble_**" instead, seemed to install the packages correctly. 

Unfortunately, I am still getting an error when I try to reinstall the plugin:
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth_hci_socket-0.5.3-8-node-v93-linux-arm.tar.gz

**Comment by xhi-nico** [comment]
Thanks for your support on this. If it's not something obvious, no need to waste time on it. Happy to use the OpenAPI that now works without the delay.

**Comment by donavanbecker** [comment]
Sorry, it is definitely something with the OS. I will close this issue.

**Comment by yjeanrenaud** [comment]
I have the same issue. also on a RPI3. are you using a x64 kernel?

**Comment by donavanbecker** [comment]
have all of you looked at: https://github.com/nodejs/node-gyp? and its requirements? 
or
https://github.com/abandonware/node-bluetooth-hci-socket? and its [prerequisites](https://github.com/abandonware/node-bluetooth-hci-socket#prerequisites)

**Comment by donavanbecker** [comment]
you could also try install:

```
sudo apt install build-essential
```

then trying to install the plugin

**Comment by yjeanrenaud** [comment]
did both. node-gyp is running, build-essentials are on latest.

**Comment by donavanbecker** [comment]
@yjeanrenaud Nothing I can do than.

**Comment by xhi-nico** [comment]
This was driving me insane and I couldn't let it go. Finally solved it, here's how:

1. Upgrade your NodeJS to the latest version 
`sudo su`
`curl -fsSL https://deb.nodesource.com/setup_18.x | bash -`
`sudo apt-get install -y nodejs`

2. Check your version and make sure NPM is installed correctly to the latest version
`nodejs -v`
`npm -v`

3. Install Noble
`npm install noble`

4. Install bluetooth-hci-socket
`npm install @abandonware/bluetooth-hci-socket`

Hopefully that works; good luck

Also don't do any of this via the homebridge terminal; make sure you're logged in via SSH.

**Comment by donavanbecker** [comment]
I have created a wiki that can help users in the future: https://github.com/OpenWonderLabs/homebridge-switchbot/wiki/Bluetooth-Issue
